UR5_joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50

# UR5 Control
UR5_shoulder_pan_joint_controller:
    type: position_controllers/JointPositionController
    joint: 'ur_arm_shoulder_pan_joint'
    pid: {p: 1.0, i: 0.0, d: 0.0}

UR5_shoulder_lift_joint_controller:
    type: position_controllers/JointPositionController
    joint: 'ur_arm_shoulder_lift_joint'
    pid: {p: 1.0, i: 0.0, d: 0.0}

UR5_elbow_joint_controller:
    type: position_controllers/JointPositionController
    joint: 'ur_arm_elbow_joint'
    pid: {p: 1.0, i: 0.0, d: 0.0}

UR5_wrist_1_joint_controller:
    type: position_controllers/JointPositionController
    joint: 'ur_arm_wrist_1_joint'
    pid: {p: 1.0, i: 0.0, d: 0.0}

UR5_wrist_2_joint_controller:
    type: position_controllers/JointPositionController
    joint: 'ur_arm_wrist_2_joint'
    pid: {p: 1.0, i: 0.0, d: 0.0}

UR5_wrist_3_joint_controller:
    type: position_controllers/JointPositionController
    joint: 'ur_arm_wrist_3_joint'
    pid: {p: 1.0, i: 0.0, d: 0.0}